DROP DATABASE IF EXISTS crossjoin;

CREATE DATABASE IF NOT EXISTS crossjoin;
USE crossjoin;

DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS orders;

CREATE TABLE customers(
    ID INT,
    NAME VARCHAR(20),
    AGE INT,
    PHONE INT);
CREATE TABLE orders(
    ORDER_ID INT,
    AMOUNT INT,
    PLACED_ON DATE);
    
INSERT INTO customers VALUES(1,'AMIT JAIN',21,98474);
INSERT INTO customers VALUES(2,'JATIN VERMA',47,63996);
INSERT INTO orders VALUES(101,999,'2023-04-19');
INSERT INTO orders VALUES(102,4999,'2023-04-20');  